### ISSUE TITLE
Shard data not found

### ISSUE THREAD

**Issue by super3** [Storj/complex#16]
### Package Versions

Replace the values below using the output from `npm list storj`.

```
Storjcli: 1.0.17 | Core: 4.1.0
```

Replace the values below using the output from `node --version`.

```
v4.5.0
```
### Expected Behavior

Upload without error.
### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
storj upload-file -k [password] -r 6 -c 3 57fd1cba26adcf743a1adc2c upfile
...
[Thu Oct 27 2016 12:13:22 GMT-0400 (EDT)] [info]   [ (2016-10-27T16;12;42.228Z)-upfile ] Encryption key saved to keyring.
 [Thu Oct 27 2016 12:13:22 GMT-0400 (EDT)] [info]   [ (2016-10-27T16;12;42.228Z)-upfile ] File successfully stored in bucket.
 [Thu Oct 27 2016 12:13:22 GMT-0400 (EDT)] [info]   Name: (2016-10-27T16;12;42.228Z)-upfile, Type: application/octet-stream, Size: 117440512 bytes, ID: a7cb6b0ea4d9c23489a19d59
 [Thu Oct 27 2016 12:13:22 GMT-0400 (EDT)] [info]   1 of 1 files uploaded
 [Thu Oct 27 2016 12:13:22 GMT-0400 (EDT)] [info]   Done.
 [Thu Oct 27 2016 12:13:31 GMT-0400 (EDT)] [error]  Error: Shard data not found<br> &nbsp; &nbsp;at Request._callback (/opt/storj/bridge/node_modules/storj-complex/lib/client.js:62:25)<br> &nbsp; &nbsp;at Request.self.callback (/opt/storj/bridge/node_modules/storj-complex/node_modules/request/request.js:186:22)<br> &nbsp; &nbsp;at emitTwo (events.js:87:13)<br> &nbsp; &nbsp;at Request.emit (events.js:172:7)<br> &nbsp; &nbsp;at Request.&lt;anonymous&gt; (/opt/storj/bridge/node_modules/storj-complex/node_modules/request/request.js:1060:10)<br> &nbsp; &nbsp;at emitOne (events.js:77:13)<br> &nbsp; &nbsp;at Request.emit (events.js:169:7)<br> &nbsp; &nbsp;at IncomingMessage.&lt;anonymous&gt; (/opt/storj/bridge/node_modules/storj-complex/node_modules/request/request.js:980:12)<br> &nbsp; &nbsp;at IncomingMessage.g (events.js:260:16)<br> &nbsp; &nbsp;at emitNone (events.js:72:20)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:166:7)<br> &nbsp; &nbsp;at endReadableNT (_stream_readable.js:913:12)<br> &nbsp; &nbsp;at nextTickCallbackWith2Args (node.js:442:9)<br> &nbsp; &nbsp;at process._tickCallback (node.js:356:17)
```
### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.
1. Upload a couple of files larger than 100 MB.
2. Sometimes you will get this error.

**Comment by MeijeSibbel** [comment]
same issue: https://github.com/Storj/bridge/issues/261

**Comment by MeijeSibbel** [comment]
This error is appearing again with the latest bridge release (v2.0.0).

```
 [Sun Nov 13 2016 23:36:15 GMT+0100 (W. Europe Standard Time)] [info]   4 of 29 files uploaded
 [Sun Nov 13 2016 23:36:16 GMT+0100 (W. Europe Standard Time)] [info]   Encrypting file "D:/movies/Concussion.2015.DVDScr.XVID.AC3.HQ.Hive-CM8.avi"
 [Sun Nov 13 2016 23:36:18 GMT+0100 (W. Europe Standard Time)] [error]  Error: Shard data not found<br> &nbsp; &nbsp;at Request._callback (/root/code/storj-complex/l
ib/client.js:61:25)<br> &nbsp; &nbsp;at Request.self.callback (/root/code/storj-complex/node_modules/request/request.js:187:22)<br> &nbsp; &nbsp;at emitTwo (events.j
s:106:13)<br> &nbsp; &nbsp;at Request.emit (events.js:191:7)<br> &nbsp; &nbsp;at Request.&lt;anonymous&gt; (/root/code/storj-complex/node_modules/request/request.js:
1048:10)<br> &nbsp; &nbsp;at emitOne (events.js:96:13)<br> &nbsp; &nbsp;at Request.emit (events.js:188:7)<br> &nbsp; &nbsp;at IncomingMessage.&lt;anonymous&gt; (/roo
t/code/storj-complex/node_modules/request/request.js:969:12)<br> &nbsp; &nbsp;at emitNone (events.js:91:20)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:185:7
)<br> &nbsp; &nbsp;at endReadableNT (_stream_readable.js:974:12)<br> &nbsp; &nbsp;at _combinedTickCallback (internal/process/next_tick.js:74:11)<br> &nbsp; &nbsp;at
process._tickDomainCallback (internal/process/next_tick.js:122:9)

```

**Comment by vevarm** [comment]
I could also reproduce this, with a file smaller than 1kB.

This was on bridge verison 2.1.0

**Comment by braydonf** [comment]
Closing as this looks outdated and we have plenty of issues to keep track of upload issues.
