### ISSUE TITLE
Error: Key not found in database

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/complex#20]
Replace the values below using the output from npm list storj.

Storjcli: 2.0.1 | Core: 5.1.2 | bridge 2.2.3
Replace the values below using the output from node --version.

v6.9.1

### Expected Behavior

Upload without error.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

storj -k meije0612 -r 12 upload-file 994ee4759cfc6292f7f5dde3 D:\Pictures\* 

```
 [Fri Nov 18 2016 20:40:33 GMT+0100 (W. Europe Standard Time)] [info]   192 of 1079 files uploaded
 [Fri Nov 18 2016 20:40:33 GMT+0100 (W. Europe Standard Time)] [warn]   [ IMG_20140920_185729.jpg ] Already exists in bucket. Uploading to (2016-11-18T19;40;33.528Z)-IMG_
0140920_185729.jpg
 [Fri Nov 18 2016 20:40:33 GMT+0100 (W. Europe Standard Time)] [info]   Encrypting file "D:/Pictures/IMG_20140920_185729.jpg"
 [Fri Nov 18 2016 20:40:35 GMT+0100 (W. Europe Standard Time)] [error]  Error: Key not found in database [01dd2c58a7a54af2026a914bab7f4246fe8c6ae0]<br> &nbsp; &nbsp;at Re
uest._callback (/opt/storj/bridge/node_modules/storj-complex/lib/client.js:61:25)<br> &nbsp; &nbsp;at Request.self.callback (/opt/storj/bridge/node_modules/request/reques
.js:186:22)<br> &nbsp; &nbsp;at emitTwo (events.js:106:13)<br> &nbsp; &nbsp;at Request.emit (events.js:191:7)<br> &nbsp; &nbsp;at Request.&lt;anonymous&gt; (/opt/storj/br
dge/node_modules/request/request.js:1081:10)<br> &nbsp; &nbsp;at emitOne (events.js:96:13)<br> &nbsp; &nbsp;at Request.emit (events.js:188:7)<br> &nbsp; &nbsp;at Incoming
essage.&lt;anonymous&gt; (/opt/storj/bridge/node_modules/request/request.js:1001:12)<br> &nbsp; &nbsp;at IncomingMessage.g (events.js:291:16)<br> &nbsp; &nbsp;at emitNone
(events.js:91:20)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:185:7)<br> &nbsp; &nbsp;at endReadableNT (_stream_readable.js:974:12)<br> &nbsp; &nbsp;at _combinedT
ckCallback (internal/process/next_tick.js:74:11)<br> &nbsp; &nbsp;at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

Upload a file

**Comment by MeijeSibbel** [comment]
Same error with the latest core release (v6.0.1):
```
 [Sat Dec 03 2016 18:29:04 GMT+0100 (W. Europe Standard Time)] [error]  Error: Shard data not found<br> &nbsp; &nbsp;at Request._callback (/root/bridge/node_modules/stor
complex/lib/client.js:61:25)<br> &nbsp; &nbsp;at Request.self.callback (/root/bridge/node_modules/request/request.js:186:22)<br> &nbsp; &nbsp;at emitTwo (events.js:106:1
<br> &nbsp; &nbsp;at Request.emit (events.js:191:7)<br> &nbsp; &nbsp;at Request.&lt;anonymous&gt; (/root/bridge/node_modules/request/request.js:1081:10)<br> &nbsp; &nbsp
t emitOne (events.js:96:13)<br> &nbsp; &nbsp;at Request.emit (events.js:188:7)<br> &nbsp; &nbsp;at IncomingMessage.&lt;anonymous&gt; (/root/bridge/node_modules/request/r
uest.js:1001:12)<br> &nbsp; &nbsp;at IncomingMessage.g (events.js:291:16)<br> &nbsp; &nbsp;at emitNone (events.js:91:20)<br> &nbsp; &nbsp;at IncomingMessage.emit (events
s:185:7)<br> &nbsp; &nbsp;at endReadableNT (_stream_readable.js:974:12)<br> &nbsp; &nbsp;at _combinedTickCallback (internal/process/next_tick.js:74:11)<br> &nbsp; &nbsp;
 process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by braydonf** [comment]
Closing as outdated.
