### ISSUE TITLE
Error: Key not found in database: take #2

### ISSUE THREAD

**Issue by vevarm** [Storj/complex#24]
see https://github.com/Storj/complex/issues/18

v6.9.1
Storjcli: 2.0.1 | Core: 5.1.2
 [Wed Nov 23 2016 13:19:10 GMT+0100 (CET)] [info]   Title:             Storj Bridge
 [Wed Nov 23 2016 13:19:10 GMT+0100 (CET)] [info]   Description:       Access the Storj network using a simple REST API.
 [Wed Nov 23 2016 13:19:10 GMT+0100 (CET)] [info]   Version:           2.2.4

[error]  Error: Key not found in database [e6301e1dcd7104c94128f820e8ea699cad2acfdf]<br> &nbsp; &nbsp;at Request._callback (/opt/storj/bridge/node_modules/storj-complex/lib/client.js:61:25)<br> &nbsp; &nbsp;at Request.self.callback (/opt/storj/bridge/node_modules/request/request.js:186:22)<br> &nbsp; &nbsp;at emitTwo (events.js:106:13)<br> &nbsp; &nbsp;at Request.emit (events.js:191:7)<br> &nbsp; &nbsp;at Request.&lt;anonymous&gt; (/opt/storj/bridge/node_modules/request/request.js:1081:10)<br> &nbsp; &nbsp;at emitOne (events.js:96:13)<br> &nbsp; &nbsp;at Request.emit (events.js:188:7)<br> &nbsp; &nbsp;at IncomingMessage.&lt;anonymous&gt; (/opt/storj/bridge/node_modules/request/request.js:1001:12)<br> &nbsp; &nbsp;at IncomingMessage.g (events.js:291:16)<br> &nbsp; &nbsp;at emitNone (events.js:91:20)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:185:7)<br> &nbsp; &nbsp;at endReadableNT (_stream_readable.js:974:12)<br> &nbsp; &nbsp;at _combinedTickCallback (internal/process/next_tick.js:74:11)<br> &nbsp; &nbsp;at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by vevarm** [comment]
This is duplicate of #20.
