### ISSUE TITLE
upload-file: Error: IO error

### ISSUE THREAD

**Issue by vevarm** [Storj/complex#28]
v6.9.1
Storjcli: 2.0.1 | Core: 5.1.2
 [Thu Nov 24 2016 02:57:33 GMT+0100 (CET)] [info]   Title:             Storj Bridge
 [Thu Nov 24 2016 02:57:33 GMT+0100 (CET)] [info]   Description:       Access the Storj network using a simple REST API.
 [Thu Nov 24 2016 02:57:33 GMT+0100 (CET)] [info]   Version:           2.2.4

Getting these errors during upload, I assume its a sharers disk area its refering to:

```

 [Thu Nov 24 2016 02:53:00 GMT+0100 (CET)] [error]  Error: IO error: Y:\New folder\cli\contracts.db/002477.ldb<br> &nbsp; &nbsp;at Request._callback (/opt/storj/bridge/node_modules/storj-complex/lib/client.js:61:25)<br> &nbsp; &nbs
p;at Request.self.callback (/opt/storj/bridge/node_modules/request/request.js:186:22)<br> &nbsp; &nbsp;at emitTwo (events.js:106:13)<br> &nbsp; &nbsp;at Request.emit (events.js:191:7)<br> &nbsp; &nbsp;at Request.&lt;anonymous&gt; (
/opt/storj/bridge/node_modules/request/request.js:1081:10)<br> &nbsp; &nbsp;at emitOne (events.js:96:13)<br> &nbsp; &nbsp;at Request.emit (events.js:188:7)<br> &nbsp; &nbsp;at IncomingMessage.&lt;anonymous&gt; (/opt/storj/bridge/no
de_modules/request/request.js:1001:12)<br> &nbsp; &nbsp;at IncomingMessage.g (events.js:291:16)<br> &nbsp; &nbsp;at emitNone (events.js:91:20)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:185:7)<br> &nbsp; &nbsp;at endReadab
leNT (_stream_readable.js:974:12)<br> &nbsp; &nbsp;at _combinedTickCallback (internal/process/next_tick.js:74:11)<br> &nbsp; &nbsp;at process._tickCallback (internal/process/next_tick.js:98:9)



```

**Comment by braydonf** [comment]
Searching through logs and I only see issue related for IO error for contracts.db for storjshare, and oddly enough for bridge (likely send from storjshare).
