### ISSUE TITLE
RabbitMQ restart/shutdown crashes the renter

### ISSUE THREAD

**Issue by braydonf** [Storj/complex#63]
```
{"level":"info","message":"replying to message to ...","timestamp":"2017-06-01T00:21:11.515Z"} events.js:160
      throw er; // Unhandled 'error' event
      ^ 
Error: Connection closed: 320 (CONNECTION-FORCED) with message "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'"
    at Object.accept (node_modules/amqplib/lib/connection.js:89:32)
    at Connection.mainAccept (node_modules/amqplib/lib/connection.js:62:33)
    at Socket.go (node_modules/amqplib/lib/connection.js:465:48)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at emitReadable_ (_stream_readable.js:432:10)
    at emitReadable (_stream_readable.js:426:7)
    at readableAddChunk (_stream_readable.js:187:13)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```

**Comment by braydonf** [comment]
This was fixed in https://github.com/Storj/complex/pull/69
