### ISSUE TITLE
Renter crashes when it cannot connect to mongos proxy

### ISSUE THREAD

**Issue by braydonf** [Storj/complex#64]
```
/storj/complex/node_modules/mongodb/lib/mongos.js:256
        process.nextTick(function() { throw err; })
                                              ^
                                              MongoError: no mongos proxy available
                                                  at Timeout.<anonymous> (/storj/complex/node_modules/mongodb-core/lib/topologies/mongos.js:638:28)
      at ontimeout (timers.js:380:14)
      at tryOnTimeout (timers.js:244:5)
      at Timer.listOnTimeout (timers.js:214:5)
  </anonymous>
```
More info: https://github.com/Storj/storj-sdk/blob/master/doc/stress-testing/test-results-05.31.17.md

**Comment by braydonf** [comment]
This was fixed in https://github.com/Storj/complex/pull/69
