### ISSUE TITLE
hdIndex is expected with hdKey

### ISSUE THREAD

**Issue by abrkn** [Storj/complex#73]
```
ubuntu@ip-172-31-31-81:~/complex$ vim storj-lib/lib/network/index.js^C
ubuntu@ip-172-31-31-81:~/complex$ ^C
ubuntu@ip-172-31-31-81:~/complex$ bin/storj-complex.js -c example/renter-config.json
{"level":"info","message":"opening database connection at mongodb://localhost:27017/__storj-complex-example","timestamp":"2017-08-13T11:51:55.701Z"}
{"level":"info","message":"connected to database","timestamp":"2017-08-13T11:51:55.781Z"}

events.js:160
      throw er; // Unhandled 'error' event
      ^
AssertionError: "hdIndex" is expected with "hdKey"
    at RenterInterface.Network._initKeyPair (/home/ubuntu/complex/node_modules/storj-lib/lib/network/index.js:88:5)
    at RenterInterface.Network (/home/ubuntu/complex/node_modules/storj-lib/lib/network/index.js:68:8)
    at new RenterInterface (/home/ubuntu/complex/node_modules/storj-lib/lib/network/renter.js:56:11)
    at Object.RenterInterface [as Renter] (/home/ubuntu/complex/node_modules/storj-lib/lib/network/renter.js:53:12)
    at Renter._initNetwork (/home/ubuntu/complex/lib/renter.js:124:24)
    at Renter.<anonymous> (/home/ubuntu/complex/lib/renter.js:163:10)
    at /home/ubuntu/complex/lib/renter.js:196:5
    at /home/ubuntu/complex/node_modules/mongoose/lib/query.js:2916:18
    at tryCatcher (/home/ubuntu/complex/node_modules/storj-service-storage-models/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ubuntu/complex/node_modules/storj-service-storage-models/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/ubuntu/complex/node_modules/storj-service-storage-models/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/ubuntu/complex/node_modules/storj-service-storage-models/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/ubuntu/complex/node_modules/storj-service-storage-models/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/ubuntu/complex/node_modules/storj-service-storage-models/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/ubuntu/complex/node_modules/storj-service-storage-models/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/ubuntu/complex/node_modules/storj-service-storage-models/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
ubuntu@ip-172-31-31-81:~/complex$
```

**Comment by braydonf** [comment]
This is a precondition in the config, not an issue. If you have questions please ask in https://community.storj.io/home
